name: Run Full Application Stack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uvicorn fastapi pydantic python-multipart requests python-dotenv openai

      - name: Build frontend
        run: npm run build

      - name: Run tests
        run: npm test || echo "No tests configured"

      - name: Start application stack
        run: |
          echo "Starting full application stack..."
          npm run start:full &
          sleep 30
          curl -f http://localhost:5173 || echo "Frontend not responding"
          curl -f http://localhost:8000/health || echo "Backend health check failed"
        timeout-minutes: 5

      - name: Cleanup
        run: pkill -f "npm|node|uvicorn" || true
