name: Test Git Identity with GITHUB_TOKEN

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make test commit
        run: |
          echo "Test run at $(date)" >> auth_test.log
          git add auth_test.log
          git commit -m "Test: commit to verify GITHUB_TOKEN auth" || echo "No changes to commit"

      - name: Push commit
        run: git push origin HEAD
